export const members = [
  {
    name: "Emmanuel AGBOTOEDO",
    role: "CEO · Chef de projet",
    focus: "Pilotage produit, delivery, relation client",
    location: "Cotonou",
    initial: "EA",
    color: "#242675",
    tags: ["Leadership", "Product", "Delivery"],
    image: "/team/emmanuel.png",
    bio: "Coordonne les projets clés, garantit la tenue des délais et la qualité de livraison.",
    linkedin: "https://www.linkedin.com",
    github: "https://github.com",
  },
  {
    name: "Jolidon HOUNGUE",
    role: "Lead Designer",
    focus: "Design system, UX/UI, accessibilité",
    location: "Cotonou",
    initial: "JH",
    color: "#f472b6",
    tags: ["Design", "UX"],
    image: "/team/placeholder.svg",
    bio: "Crée des expériences cohérentes web/mobile, design systems scalables, focus accessibilité.",
    linkedin: "#",
    github: "#",
  },
  {
    name: "Billa ASSUMA",
    role: "Lead Engineer",
    focus: "Architecture cloud, performance, sécurité",
    location: "Lyon",
    initial: "BA",
    color: "#a78bfa",
    tags: ["Backend", "Cloud"],
    image: "/team/placeholder.svg",
    bio: "Architecture cloud-native, observabilité et SLO en production.",
    linkedin: "#",
    github: "#",
  },
  {
    name: "David IDOHOU",
    role: "Lead Developer",
    focus: "Architecture, développement senior, mentoring",
    location: "Cotonou",
    initial: "DI",
    color: "#06b6d4",
    tags: ["Engineering", "Product"],
    image: "/team/placeholder.svg",
    bio: "Lead Developer avec expertise en architecture et mentorat d'équipes de développement.",
    linkedin: "#",
    github: "#",
  },
  {
    name: "Jean-Paul GINKPO",
    role: "Developpeur Backend",
    focus: "API REST, bases de données, infrastructure",
    location: "Cotonou",
    initial: "JG",
    color: "#8b5cf6",
    tags: ["Backend", "Engineering"],
    image: "/team/placeholder.svg",
    bio: "Développeur Backend spécialisé dans la conception d'API robustes et scalables.",
    linkedin: "#",
    github: "#",
  },
  {
    name: "Epiphane HOUEHANOU",
    role: "Developpeur Fullstack",
    focus: "Frontend, backend, deployment",
    location: "Cotonou",
    initial: "EH",
    color: "#ec4899",
    tags: ["Engineering", "Product"],
    image: "/team/placeholder.svg",
    bio: "Développeur Fullstack capable de gérer tous les niveaux de la stack applicative.",
    linkedin: "#",
    github: "#",
  },
];

export const filters = [
  "Tous",
  "Product",
  "Engineering",
  "Design",
  "AI/ML",
  "Mobile",
  "Delivery",
  "Hiring",
];
