export const members = [
  {
    name: "Emmanuel AGBOTOEDO",
    role: "CEO · Chef de projet",
    focus: "Pilotage produit, delivery, relation client",
    location: "Cotonou",
    initial: "EA",
    color: "#242675",
    tags: ["Leadership", "Product", "Delivery"],
    image: "/team/emmanuel.png",
    bio: "Coordonne les projets clés, garantit la tenue des délais et la qualité de livraison.",
    linkedin: "https://www.linkedin.com",
    github: "https://github.com",
  },
  {
    name: "Jolidon HOUNGUE",
    role: "Lead Designer",
    focus: "Design system, UX/UI, accessibilité",
    location: "Cotonou",
    initial: "JH",
    color: "#f472b6",
    tags: ["Design", "UX"],
    image: "/team/placeholder.svg",
    bio: "Crée des expériences cohérentes web/mobile, design systems scalables, focus accessibilité.",
    linkedin: "#",
    github: "#",
  },
  {
    name: "Billa ASSUMA",
    role: "Lead Engineer",
    focus: "Architecture cloud, performance, sécurité",
    location: "Lyon",
    initial: "BA",
    color: "#a78bfa",
    tags: ["Backend", "Cloud"],
    image: "/team/placeholder.svg",
    bio: "Architecture cloud-native, observabilité et SLO en production.",
    linkedin: "#",
    github: "#",
  },
  {
    name: "Sara Benali",
    role: "Lead Designer",
    focus: "Design system, UX research, accessibilité",
    location: "Marseille",
    initial: "SB",
    color: "#f472b6",
    tags: ["Design", "UX"],
    image: "/team/placeholder.svg",
    bio: "UX research, design system multi-plateforme, accessibilité AA.",
    linkedin: "#",
    github: "#",
  },
  {
    name: "Victor Chen",
    role: "Data/AI Lead",
    focus: "Pipelines, LLM apps, MLOps",
    location: "Remote · NYC",
    initial: "VC",
    color: "#242675",
    tags: ["AI/ML", "Data"],
    image: "/team/placeholder.svg",
    bio: "Copilots LLM, RAG, déploiements sécurisés et monitoring coût/latence.",
    linkedin: "#",
    github: "#",
  },
  {
    name: "Camille Roux",
    role: "Mobile Lead",
    focus: "React Native, performances, stores",
    location: "Remote · Montréal",
    initial: "CR",
    color: "#fb923c",
    tags: ["Mobile", "React Native"],
    image: "/team/placeholder.svg",
    bio: "Apps React Native store-ready avec crash rate <0.2% et perf optimisée.",
    linkedin: "#",
    github: "#",
  },
  {
    name: "Amine Haddad",
    role: "Delivery Manager",
    focus: "Roadmaps, rituels, qualité, risques",
    location: "Remote · Tunis",
    initial: "AH",
    color: "#facc15",
    tags: ["Delivery", "Ops"],
    image: "/team/placeholder.svg",
    bio: "Coordination des squads, gestion risques, mise en prod en continu.",
    linkedin: "#",
    github: "#",
  },
  {
    name: "Vous ?",
    role: "Rejoindre la squad",
    focus: "Design, front, backend, data/AI — missions seniors.",
    location: "Remote",
    initial: "★",
    color: "#3E4347",
    tags: ["Hiring"],
    image: "/team/placeholder.svg",
    bio: "On recrute des profils seniors pour des missions courtes et exigeantes.",
    linkedin: "/contact",
    github: "",
  },
];

export const filters = ["Tous", "Product", "Engineering", "Design", "AI/ML", "Mobile", "Delivery", "Hiring"];
