export const services = [
  {
    id: "web",
    icon: "◈",
    label: "Web",
    title: "Produits web",
    tagline: "SaaS, dashboards, back-office",
    desc: "On conçoit et développe des produits web B2B/B2C ambitieux de l'architecture API jusqu'au design system pensés pour scaler dès le premier sprint.",
    accent: "#242675",
    tags: ["Next.js", "Node", "Postgres", "Edge"],
    points: [
      "Architecture multi-tenant dès J1",
      "Perf Core Web Vitals ≥ 90",
      "Auth, RBAC, billing Stripe intégrés",
      "CI/CD Vercel + monitoring Datadog",
    ],
    stat: { val: "< 6", unit: "sem.", label: "pour un MVP en prod" },
  },
  {
    id: "mobile",
    icon: "◉",
    label: "Mobile",
    title: "Apps mobiles",
    tagline: "iOS, Android, design system",
    desc: "Des applications React Native hautes performances, cohérentes sur les deux stores, avec un design system partagé entre web et mobile pour aller vite sans sacrifier la qualité.",
    accent: "#242675",
    tags: ["React Native", "Expo", "Supabase", "Stores"],
    points: [
      "Shared design system web ↔ mobile",
      "Publication simultanée iOS & Android",
      "Crash rate < 0.2% garanti",
      "Push, deep links, offline ready",
    ],
    stat: { val: "50k", unit: "MAU", label: "en 2 mois (ref. santé)" },
  },
  {
    id: "data",
    icon: "⬡",
    label: "Data / AI",
    title: "Data & AI",
    tagline: "Pipelines, LLM, copilots métier",
    desc: "De l'ingestion à la mise en production de modèles pipelines data robustes, RAG sur vos documents internes, copilots LLM et observabilité ML ops pour des systèmes fiables.",
    accent: "#a78bfa",
    tags: ["Python", "LLM", "RAG", "OpenSearch", "MLOps"],
    points: [
      "RAG sur vos bases documentaires",
      "LLM ops : eval, coûts, latence",
      "Pipelines dbt + Airflow + datalake",
      "Dashboards décisionnels temps réel",
    ],
    stat: { val: "−30%", unit: "L1", label: "support après copilot (ref.)" },
  },
  {
    id: "ops",
    icon: "▲",
    label: "Product Ops",
    title: "Product Ops",
    tagline: "Roadmaps, growth, analytics",
    desc: "Un regard senior sur votre stratégie produit : instrumentation analytics, optimisation du funnel, OKRs, rituels agiles et growth loops pour transformer les données en décisions.",
    accent: "#fb923c",
    tags: ["Analytics", "SEO", "Growth", "OKRs"],
    points: [
      "Audit produit & instrumentation",
      "Funnel, rétention, activation",
      "SEO technique & content strategy",
      "Rituels agiles & reporting exec",
    ],
    stat: { val: "+42%", unit: "conv.", label: "demo → contrat (ref.)" },
  },
  {
    id: "ecommerce",
    icon: "◎",
    label: "E-commerce",
    title: "E-commerce",
    tagline: "Boutiques, payment gateway, logistics",
    desc: "Des expériences d'achat fluides et conversionnelles intégration complète paiements (Stripe, PayPal), gestion des stocks en temps réel, optimisation mobile pour maximiser vos conversions.",
    accent: "#06b6d4",
    tags: ["Next.js", "Shopify", "Stripe", "Logistics"],
    points: [
      "UX conversion optimisée (mobile-first)",
      "Paiements sécurisés multi-devise",
      "Gestion stocks & inventory en temps réel",
      "SEO e-commerce & analytics conversion",
    ],
    stat: { val: "+32%", unit: "ventes", label: "en ligne (ref.)" },
  },
  {
    id: "design",
    icon: "✦",
    label: "UX/Design",
    title: "UX/Design",
    tagline: "Design systems, Figma, prototypage",
    desc: "Des systèmes de design maintenables et évolutifs, prototypage interactif haute-fidélité, composants réutilisables et documentation pour aligner toute votre équipe produit.",
    accent: "#ec4899",
    tags: ["Figma", "Design System", "Prototyping", "UI/UX"],
    points: [
      "Design system tokens et composants",
      "Prototypes interactifs et testables",
      "Documentation composants intégrée",
      "Audit UX et recommendations",
    ],
    stat: { val: "80h", unit: "économisées", label: "par trim. (ref.)" },
  },
  {
    id: "strategy",
    icon: "⟡",
    label: "Conseil & Strategy",
    title: "Conseil & Strategy",
    tagline: "Architecture logicielle, roadmaps tech",
    desc: "Expertise senior en architecture logicielle, modernisation des stacks legacy, roadmaps techniques alignées métier et stratégies de scalabilité pour pérenniser votre produit.",
    accent: "#8b5cf6",
    tags: ["Architecture", "Legacy Modernization", "Tech Strategy", "Scalability"],
    points: [
      "Audit architecture et recommendations",
      "Roadmap technique 12-24 mois",
      "Migration et refactoring dirigés",
      "Formation équipe sur patterns modernes",
    ],
    stat: { val: "−60%", unit: "dette tech", label: "en 6 mois (ref.)" },
  },
  {
    id: "testing",
    icon: "✓",
    label: "Testing & QA",
    title: "Testing & QA",
    tagline: "Automatisation, E2E, performance, sécurité",
    desc: "Stratégies testing exhaustives, automatisation des tests E2E, performance benchmarking et audits de sécurité pour garantir une qualité d'entreprise en production.",
    accent: "#10b981",
    tags: ["Cypress", "Playwright", "Performance", "Security"],
    points: [
      "Suites E2E et tests unitaires",
      "Performance & Core Web Vitals audit",
      "Audit sécurité & OWASP compliance",
      "Load testing et stress testing",
    ],
    stat: { val: "0", unit: "bugs", label: "en prod (SLA 99.9%)" },
  },
  {
    id: "support",
    icon: "⊗",
    label: "Maintenance & Support",
    title: "Maintenance & Support",
    tagline: "Monitoring 24/7, optimisation, maintenance",
    desc: "Support technique 24/7, monitoring et alertes proactives, optimisations de performance continues et maintenance préventive pour assurer la stabilité de vos systèmes.",
    accent: "#f59e0b",
    tags: ["Datadog", "Monitoring", "DevOps", "SRE"],
    points: [
      "Monitoring et alertes 24/7",
      "Optimisation performance continue",
      "Patch management et security updates",
      "RCA et incident post-mortems",
    ],
    stat: { val: "99.95%", unit: "uptime", label: "garanti (ref.)" },
  },
  {
    id: "integrations",
    icon: "◇",
    label: "Intégrations & APIs",
    title: "Intégrations & APIs",
    tagline: "Webhooks, APIs tierces, migrations data",
    desc: "Intégrations seamless avec les plateformes tierces, construction d'APIs robustes, migrations data complexes et gestion des webhooks pour ecosystèmes interconnectés.",
    accent: "#06b6d4",
    tags: ["APIs", "Webhooks", "Data Migration", "Integrations"],
    points: [
      "Design et build APIs RESTful/GraphQL",
      "Intégrations avec 100+ services",
      "Migrations data zéro downtime",
      "Webhook management et retry logic",
    ],
    stat: { val: "0", unit: "downtime", label: "lors migration (ref.)" },
  },
  {
    id: "security",
    icon: "🔒",
    label: "Sécurité",
    title: "Sécurité",
    tagline: "Audit, compliance, encryption",
    desc: "Audits de sécurité approfondis, conformité GDPR/RGPD, implémentation du chiffrement end-to-end et pentesting régulier pour protéger vos données et celle de vos utilisateurs.",
    accent: "#ef4444",
    tags: ["Security Audit", "GDPR", "Encryption", "Compliance"],
    points: [
      "Audit de sécurité et pentesting",
      "Conformité GDPR et compliance",
      "Encryption et key management",
      "Security policies et training équipe",
    ],
    stat: { val: "0", unit: "breaches", label: "certifié SOC2 (ref.)" },
  },
  ];

export const process = [
  { step: "01", title: "Discovery", desc: "Cadrage produit, personas, parcours critiques, périmètre MVP en 3 jours.", duration: "J1-3" },
  { step: "02", title: "Design", desc: "Design system express, maquettes haute fidélité, prototypage interactif.", duration: "J4-8" },
  { step: "03", title: "Build", desc: "Sprints de 2 semaines, démos client, CI/CD dès J+14, qualité continue.", duration: "J9-35" },
  { step: "04", title: "Launch", desc: "Mise en prod, instrumentation analytics, SEO, SLO. Équipe autonomisée.", duration: "J36-42" },
];
