export const services = [
  {
    id: "web",
    icon: "◈",
    label: "Web",
    title: "Produits web",
    tagline: "SaaS, dashboards, back-office",
    desc: "On conçoit et développe des produits web B2B/B2C ambitieux — de l'architecture API jusqu'au design system — pensés pour scaler dès le premier sprint.",
    accent: "#242675",
    tags: ["Next.js", "Node", "Postgres", "Edge"],
    points: [
      "Architecture multi-tenant dès J1",
      "Perf Core Web Vitals ≥ 90",
      "Auth, RBAC, billing Stripe intégrés",
      "CI/CD Vercel + monitoring Datadog",
    ],
    stat: { val: "< 6", unit: "sem.", label: "pour un MVP en prod" },
  },
  {
    id: "mobile",
    icon: "◉",
    label: "Mobile",
    title: "Apps mobiles",
    tagline: "iOS, Android, design system",
    desc: "Des applications React Native hautes performances, cohérentes sur les deux stores, avec un design system partagé entre web et mobile pour aller vite sans sacrifier la qualité.",
    accent: "#242675",
    tags: ["React Native", "Expo", "Supabase", "Stores"],
    points: [
      "Shared design system web ↔ mobile",
      "Publication simultanée iOS & Android",
      "Crash rate < 0.2% garanti",
      "Push, deep links, offline ready",
    ],
    stat: { val: "50k", unit: "MAU", label: "en 2 mois (ref. santé)" },
  },
  {
    id: "data",
    icon: "⬡",
    label: "Data / AI",
    title: "Data & AI",
    tagline: "Pipelines, LLM, copilots métier",
    desc: "De l'ingestion à la mise en production de modèles — pipelines data robustes, RAG sur vos documents internes, copilots LLM et observabilité ML ops pour des systèmes fiables.",
    accent: "#a78bfa",
    tags: ["Python", "LLM", "RAG", "OpenSearch", "MLOps"],
    points: [
      "RAG sur vos bases documentaires",
      "LLM ops : eval, coûts, latence",
      "Pipelines dbt + Airflow + datalake",
      "Dashboards décisionnels temps réel",
    ],
    stat: { val: "−30%", unit: "L1", label: "support après copilot (ref.)" },
  },
  {
    id: "ops",
    icon: "▲",
    label: "Product Ops",
    title: "Product Ops",
    tagline: "Roadmaps, growth, analytics",
    desc: "Un regard senior sur votre stratégie produit : instrumentation analytics, optimisation du funnel, OKRs, rituels agiles et growth loops pour transformer les données en décisions.",
    accent: "#fb923c",
    tags: ["Analytics", "SEO", "Growth", "OKRs"],
    points: [
      "Audit produit & instrumentation",
      "Funnel, rétention, activation",
      "SEO technique & content strategy",
      "Rituels agiles & reporting exec",
    ],
    stat: { val: "+42%", unit: "conv.", label: "demo → contrat (ref.)" },
  },
  {
    id: "ecommerce",
    icon: "◎",
    label: "E-commerce",
    title: "E-commerce",
    tagline: "Boutiques, payment gateway, logistics",
    desc: "Des expériences d'achat fluides et conversionnelles — intégration complète paiements (Stripe, PayPal), gestion des stocks en temps réel, optimisation mobile pour maximiser vos conversions.",
    accent: "#06b6d4",
    tags: ["Next.js", "Shopify", "Stripe", "Logistics"],
    points: [
      "UX conversion optimisée (mobile-first)",
      "Paiements sécurisés multi-devise",
      "Gestion stocks & inventory en temps réel",
      "SEO e-commerce & analytics conversion",
    ],
    stat: { val: "+32%", unit: "ventes", label: "en ligne (ref.)" },
  },
];

export const process = [
  { step: "01", title: "Discovery", desc: "Cadrage produit, personas, parcours critiques, périmètre MVP — en 3 jours.", duration: "J1–3" },
  { step: "02", title: "Design", desc: "Design system express, maquettes haute fidélité, prototypage interactif.", duration: "J4–8" },
  { step: "03", title: "Build", desc: "Sprints de 2 semaines, démos client, CI/CD dès J+14, qualité continue.", duration: "J9–35" },
  { step: "04", title: "Launch", desc: "Mise en prod, instrumentation analytics, SEO, SLO. Équipe autonomisée.", duration: "J36–42" },
];
